# Generated by Django 6.0.5 on 2026-05-14 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBookCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('authors', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='TermDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('normalized_term', models.CharField(db_index=True, max_length=255)),
                ('definition', models.TextField()),
                ('source_chapter', models.CharField(blank=True, max_length=255)),
                ('source_paragraph_index', models.PositiveIntegerField(default=0)),
                ('source_quote', models.TextField(blank=True)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('global_cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='books.globalbookcache')),
            ],
            options={
                'ordering': ('term',),
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('authors', models.CharField(blank=True, max_length=512)),
                ('original_filename', models.CharField(max_length=512)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file', models.FileField(blank=True, null=True, upload_to='books/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_protected', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('global_cache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_books', to='books.globalbookcache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='UserTermEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_definition', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_edits', to='books.termdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_edits', to=settings.AUTH_USER_MODEL)),
                ('user_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_edits', to='books.userbook')),
            ],
        ),
        migrations.AddIndex(
            model_name='termdefinition',
            index=models.Index(fields=['global_cache', 'term'], name='books_termd_global__eeda52_idx'),
        ),
        migrations.AddIndex(
            model_name='termdefinition',
            index=models.Index(fields=['global_cache', 'normalized_term'], name='books_termd_global__fdf371_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='termdefinition',
            unique_together={('global_cache', 'normalized_term')},
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'uploaded_at'], name='books_userb_user_id_f3dbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'status'], name='books_userb_user_id_f00db1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertermedit',
            unique_together={('user_book', 'term_definition')},
        ),
    ]
